spring:
  # 数据源
  datasource:
    username: root
    password: 13762539019whxA
    url: jdbc:mysql://localhost:3306/onlinemallcake?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  # 连接池
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 20
        keep-alive: 120s
      thread-name-prefix: omc-goods-service-
# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wu.common.domain

#分布式配置
dubbo:
  #应用名称
  application:
    name: omc-goods
  #配置注册中心
  registry:
    address: zookeeper://180.76.136.123:2181?backup=110.42.224.33:2181,39.96.61.59:2181
    timeout: 25000
    dynamic: true
  # 注册服务采用的协议 端口号
  protocol:
    name: dubbo
    port: 20881
  config-center:
    timeout: 25000
  provider:
    timeout: 10000
    dynamic: true
  consumer:
    timeout: 10000
    check: true
#端口
server:
  port: 13401