#数据源
spring:
  datasource:
    username: root
    password: 13762539019whxA
    url: jdbc:mysql://localhost:3306/onlinemallcake?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 20
        keep-alive: 120s
      thread-name-prefix: omc-user-service-
  # redis 缓存
  redis:
    sentinel:
      nodes: 180.76.136.123:26380,110.42.224.33:26380,39.96.61.59:26380
      master: mymaster
      password: banbanda
    password: banbanda
    jedis:
      pool:
        max-active: 40
        max-wait: 5000
        max-idle: 8
        min-idle: 2
    lettuce:
      pool:
        max-active: 8     #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 5     #连接池中的最大空闲连接
        min-idle: 1     #连接池中的最小空闲连接
      shutdown-timeout: 0
    timeout: 20000

# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wu.common.domain

#分布式配置
dubbo:
  #应用名称
  application:
    name: omc-user
  #配置注册中心
  registry:
    address: zookeeper://180.76.136.123:2181?backup=110.42.224.33:2181,39.96.61.59:2181
    timeout: 25000
    dynamic: true
    check: false
  # 注册服务采用的协议 端口号
  protocol:
    name: dubbo
    port: 20882
  config-center:
    timeout: 25000
  provider:
    timeout: 10000
    dynamic: true
  consumer:
    timeout: 10000
    check: true
#端口
server:
  port: 13402